title: modular

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        inhalt:
          type: tab
          title: THEME_SIMPLICITY.ADMIN.TAB.CONTENT
          fields:
            header.title:
              type: text
              autofocus: true
              label: THEME_SIMPLICITY.ADMIN.FIELDS.TITLE.LABEL

            header.tags:
              type: selectize
              label: THEME_SIMPLICITY.ADMIN.FIELDS.TAGS.LABEL
              classes: fancy
              help: PLUGIN_ADMIN.TAXONOMY_TYPES_HELP
              validate:
                type: commalist
            preview:
              type: section
              title: THEME_SIMPLICITY.ADMIN.SECTION.PREVIEW
              underline: true
              fields:
                header.preview.image:
                  type: file
                  label: THEME_SIMPLICITY.ADMIN.FIELDS.PREVIEW_IMAGE.LABEL
                  destination: '@self/preview'
                header.preview.text:
                  type: textarea
                  rows: 6
                  label: THEME_SIMPLICITY.ADMIN.FIELDS.PREVIEW_TEXT.LABEL
                  validate:
                    required: true
            content:
              type: section
              title: THEME_SIMPLICITY.ADMIN.SECTION.CONTENT
              underline: true
              fields:
                header.text:
                  type: markdown
                  validate:
                    type: textarea
